[environment]
# Matches `requires-python` in pyproject.toml
python-version = "3.10"

[rules]
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unused-ignore-comment = "error"


[[overrides]] 
include = ["tests/*.py"]

[overrides.rules]
possibly-unresolved-reference = "ignore"